import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import HeaderWrapper from "./Components/ui/HeaderWrapper";
import { ToastProvider } from "./Components/ui/ToastContext";
import { ThemeProvider } from "./Components/ui/ThemeProvider";
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import Footer from "./Components/ui/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full overflow-hidden dark">
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark:bg-BgWalaBlack light:bg-[#F9FAFB] dark:text-white light:text-[#1F2937] h-full overflow-hidden flex flex-col`}>
        <ThemeProvider>
          <ToastProvider>
            <div className="relative h-full w-full flex flex-col overflow-hidden">
              {/* Global background layers */}
              <div className="pointer-events-none fixed inset-0 z-0">
                <div
                  className="absolute inset-0 opacity-85 bg-aurora dark:opacity-85 light:opacity-0"
                  style={{
                    backgroundImage: 'radial-gradient(620px 360px at 12% 12%,rgba(56,189,248,0.14),transparent 60%),radial-gradient(520px 340px at 88% 18%,rgba(249,115,22,0.18),transparent 60%),radial-gradient(420px 300px at 50% 85%,rgba(167,139,250,0.12),transparent 65%)'
                  }}
                />
                <div
                  className="absolute inset-0 opacity-40 bg-sheen dark:opacity-40 light:opacity-0"
                  style={{
                    backgroundImage: 'conic-gradient(from 200deg at 50% 45%,rgba(255,255,255,0.05),transparent 40%,rgba(255,255,255,0.04),transparent 70%,rgba(255,255,255,0.05))'
                  }}
                />
                <div
                  className="absolute inset-0 opacity-25 bg-grid dark:opacity-25 light:opacity-0"
                  style={{
                    backgroundImage: 'linear-gradient(rgba(255,255,255,0.05) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,0.05) 1px,transparent 1px)',
                    backgroundSize: '28px 28px'
                  }}
                />
              </div>

              <div className="relative z-10 flex flex-col h-full min-h-0">
                <HeaderWrapper />
                <main className="flex-1 overflow-y-auto overflow-x-hidden">
                  {children}
                </main>
                <Footer />
              </div>
            </div>
          </ToastProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
